paths:
  data_dir: "./knowledge_base/data"
  storage_dir: "./knowledge_base/storage"
  datasets_dir: "./datasets/"
  results_dir: "./results/"

ollama:
  base_url: "http://127.0.0.1:11434"
  llm:
    model: "qwen3-vl:30b-a3b-instruct"
    request_timeout: 3600.0
    context_window: 32768
    keep_alive: "24h"
  eval_llm:
    model: "gemma3:27b"
    request_timeout: 3600.0
    context_window: 36864
    keep_alive: "24h"
  embedding:
    model_name: "qwen3-embedding:4b"

text_splitter:
  chunk_size: 512
  chunk_overlap: 50

rag:
  similarity_top_k: 5
